-- Inserting default 
INSERT INTO BL_3NF.CE_PAYMENT_METHODS (PAYMENT_METHOD_ID, PAYMENT_METHOD, PAYMENT_SRC_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PAYMENT_METHODS WHERE PAYMENT_METHOD_ID = -1);
COMMIT;


INSERT INTO BL_3NF.CE_DEALSIZES (DEALSIZE_ID, DEALSIZE, DEALSIZE_SRC_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_DEALSIZES WHERE DEALSIZE_ID = -1);
COMMIT;


INSERT INTO BL_3NF.CE_PRODUCTS (PRODUCT_ID, PRODUCTCODE, PRODUCTLINE, PRICEEACH, MSRP, PRODUCT_SRC_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', -1, -1, 'n. a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_PRODUCTS WHERE PRODUCT_ID = -1);
COMMIT;


INSERT INTO BL_3NF.CE_ORDERS (ORDERNUMBER, QUANTITYORDERED, SALES, PAYMENT_METHOD_ID, DEALSIZE_ID, PRODUCT_ID, CUSTOMER_ID, EVENT_DT, TA_INSERT_DT, TA_UPDATE_DT, ORDER_SRC_ID, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, -1, -1, -1, -1, -1, -1, '1900-01-01', '1900-01-01', '1900-01-01', 'n. a.', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_ORDERS WHERE ORDERNUMBER = -1);
COMMIT;



INSERT INTO BL_3NF.CE_CUSTOMERS_SCD (CUSTOMER_ID, CUSTOMERNAME, CONTACTFIRSTNAME, CONTACTLASTNAME, PHONE, CUSTOMER_SRC_ID, ADDRESS_ID, START_DT, END_DT, IS_ACTIVE, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', 'n. a.', 'n. a.', 'n. a.', -1, '1900-01-01', '9999-12-31', 'Y', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CUSTOMERS_SCD WHERE CUSTOMER_ID = -1);
COMMIT;


INSERT INTO BL_3NF.CE_ADDRESSES (ADDRESS_ID, ADDRESSLINE1, ADDRESS_SRC_ID, CITY_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_ADDRESSES WHERE ADDRESS_ID = -1);
COMMIT;

INSERT INTO BL_3NF.CE_STATES (STATE_ID, STATE_NAME, STATE_SRC_ID, COUNTRY_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_STATES WHERE STATE_ID = -1);
COMMIT;

INSERT INTO BL_3NF.CE_CITIES (CITY_ID, CITY_NAME, CITY_SRC_ID, STATE_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_CITIES WHERE CITY_ID = -1);
COMMIT;


INSERT INTO BL_3NF.CE_COUNTRIES (COUNTRY_ID, COUNTRY_NAME, COUNTRY_SRC_ID, TA_INSERT_DT, TA_UPDATE_DT, SOURCE_SYSTEM, SOURCE_ENTITY)
SELECT -1, 'n. a.', 'n. a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL'
WHERE NOT EXISTS (SELECT 1 FROM BL_3NF.CE_COUNTRIES WHERE COUNTRY_ID = -1);
COMMIT;

